### ISSUE TITLE
Please stop subscribing MSFT employees

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/linguisticreview#118]
Hi, I'm not sure what actions are causing this, but I've been repeatedly "subscribed" to this repo, which basically just spams my email inbox and github notifications.

Would you please limit the scope of repo collaborators to something less than the entire company?

Thanks.

**Comment by mattmazzola** [comment]
Yes, can confirm spam behavior.

Normally when a new repo is created people in the org are automatically set to watch it and we manually unwatch, but even after doing that I was still receiving notifications for every issue opened and closed.

**Comment by TomShinder** [comment]
Agree – it’s really bad.

**Comment by brminnick** [comment]
You can unsubscribe from the repo by selecting "Unwatch" at the top of the page

![screen shot 2017-06-20 at 1 44 21 pm](https://user-images.githubusercontent.com/13558917/27355099-99f5276a-55be-11e7-9bd2-0a05ca670593.png)

**Comment by gardnerjr** [comment]
sure, we *can*.  but that means like 3k people have to do that manually, every time a new repo gets created.

**Comment by tannergooding** [comment]
@gardnerjr, that is the purpose of the `Automatically watch repositories` settings under your Account:
![image](https://user-images.githubusercontent.com/10487869/27355875-561bc2ee-55c1-11e7-82af-ba8e39cbb901.png)

**Comment by gardnerjr** [comment]
yes, "when given *push* access to a repository".  most of these repositories are created by default so that *anyone inside microsoft* can just push to it, which shouldn't be the default behavior.

this is why the first person said:

> Would you please limit the scope of repo collaborators to something less than the entire company?

**Comment by benjamin-bader** [comment]
@brminnick sure, we _can_ unsubscribe, but I've done that probably four or five times now since June 1st.  Something is re-subscribing us.  A surefire way to prevent this is to limit the number of collaborators, preferably to a smaller group than all of Microsoft.

I'd be grateful if you or someone else with admin rights here would do that.

**Comment by souptc** [comment]
+1

**Comment by shailenggupta** [comment]
+1
