### ISSUE TITLE
PTB:SQL17:Falta tradução [id_10605040104_96.otp]

### ISSUE THREAD

**Issue by SQLCrespi** [Microsoft/linguisticreview#119]
<p><span style="font-family: 'Arial';font-size: 14px;">&nbsp;</span></p><p><span style="font-family: 'Arial';font-size: 14px;">argumentos opcionais:</span></p><p><span style="font-family: 'Arial';font-size: 14px;">-h, --help exibe esta mensagem de ajuda sai</span></p>

**Comment by v-zbing** [comment]
CSINTL bug: Bug 52652:PTB: SQL17: SQL Server on Linux: strings for optional arguments are not translated (10605040104)

**Comment by Monasr** [comment]
Resolved as external since the string comes from Linux. Thank you!
