### ISSUE TITLE
DEU:SQL17:type in "Protokollese-Agent" [id_10108010610_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#488]
<p><span style="font-family: 'Arial';font-size: 14px;">should be changed to &quot;Prokoll-Lese-Agent&quot;</span></p>

**Comment by v-yanwlu** [comment]
Bug: https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53193

**Comment by Monasr** [comment]
Fixed in latest build
