### ISSUE TITLE
DEU:SQL17:wrong grammar in "für BackupDevice" [id_10107010107_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#490]
<p><span style="font-family: 'Arial';font-size: 14px;">should be &quot;von BackupDevice&quot; instead</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53211

**Comment by Monasr** [comment]
Fixed
