### ISSUE TITLE
DEU:SQL17:"Zurückgestellte Abfragen" does not make sense in this context [id_10603300117_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#495]
<p><span style="font-family: 'Arial';font-size: 14px;">should be &quot;Langsamer gewordene Abfragen&quot;</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53188

**Comment by Monasr** [comment]
The issue is fixed
