### ISSUE TITLE
DEU:SQL17:"Hohe Verfügbarkeit" is not usual technical term [id_10603310102_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#496]
<p><span style="font-family: 'Arial';font-size: 14px;">&quot;Hochverf&uuml;gbarkeit&quot; is the right technical term</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53187

**Comment by Monasr** [comment]
Fix is implemented in latest build
