### ISSUE TITLE
DEU:SQL17:"Anfügen" is the wrong technical term [id_10603310103_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#497]
<p><span style="font-family: 'Arial';font-size: 14px;">&quot;Anh&auml;ngen&quot; is right technical term here</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53186

**Comment by Monasr** [comment]
Based on the feedback we got from the vendor it seems to be preferential and the issue is resolved by dedign, please let us know you disagree
