### ISSUE TITLE
DEU:SQL17:wrong grammar [id_10603390107_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#533]
<p><span style="font-family: 'Arial';font-size: 14px;">&quot;Fehler bei Erstellen&quot; should be &quot;Fehler beim Erstellen&quot; instead</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=53441

**Comment by Monasr** [comment]
The issue is fixed in latest build and should be in RC2 release
