### ISSUE TITLE
DEU:SQL17:Weird grammar in "Es kann erforderlich sein, zuerst den Besitz an Schemas auf neue Benutzer zu übertragen." [id_10603230119_96.otp]

### ISSUE THREAD

**Issue by MEhrenmueller** [Microsoft/linguisticreview#562]
<p><span style="font-family: 'Arial';font-size: 14px;">please correct to </span></p><p><span style="font-family: 'Arial';font-size: 14px;">&quot;</span><span style="font-family: 'Arial';font-size: 12.8px;color: #222222;background-color: #FFFFFF;">Es kann erforderlich sein, zuerst den Besitz eines Schemas auf einen neuen Benutzer zu &uuml;bertragen.</span><span style="font-family: 'Arial';font-size: 14px;">&quot;</span></p>

**Comment by v-zbing** [comment]
https://vstf-us-wa-05.partners.extranet.microsoft.com:8443/tfs/CEINTL/CSINTL/_workitems?_a=edit&id=54080

**Comment by Monasr** [comment]
The issue is fixed in latest build and should be in RC2 release
